myproject/myproject/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bookmarks.views.index', name='home'),
    url(r'^bookmarks/$', 'bookmarks.views.index', name='bookmarks_view'),
    url(r'^tags/([\w-]+)/$', 'bookmarks.views.tag'),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)

myproject/bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    author = models.ForeignKey(User)
    url = models.URLField()
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=200, blank=True, default="")
    
    def __unicode__(self):
        return "%s by %s" % (self.url, self.author.username)
    
    
class Tag(models.Model):
    bookmarks = models.ManyToManyField(Bookmark)
    slug = models.CharField(max_length=50, unique=True)
    
    def __unicode__(self):
        return self.slug

myproject/bookmarks/forms.py
from django import forms
from bookmarks.models import Bookmark
 
 
class BookmarkForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        fields= ('author', 'url', 'title')
        widgets = {
            'author': forms.HiddenInput(),
        }
    tags = forms.CharField(max_length=100, required=False)

myproject/bookmarks/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from bookmarks.models import Bookmark, Tag
from bookmarks.forms import BookmarkForm
import urllib

 
def index(request):
    if request.method == "POST":
        form = BookmarkForm(request.POST)
        if form.is_valid():
            new_bookmark = form.save()
            raw_tags = form.cleaned_data['tags'].split(',')
            if raw_tags:
                for raw_tag in raw_tags:
                    raw_tag = raw_tag.strip().replace(' ', '-').lower()
                    tag_slug = urllib.quote(raw_tag)
                    tag, created = Tag.objects.get_or_create(slug=tag_slug)
                    tag.save()
                    tag.bookmarks.add(new_bookmark)
            if request.is_ajax():
                return render(request, 'bookmark.html', {'bookmark': new_bookmark})
            return redirect(index)
        else:
            response = 'Errors: '
            for key in form.errors.keys():
                value = form.errors[key]
                errors = ''
                for error in value:
                    errors = errors + error + ' '
                    response = response + ' ' + key + ': ' + errors
            return HttpResponse('<li class="error">' + response + '</li>')
    bookmarks = Bookmark.objects.all().order_by('-timestamp')[:10]
    current_user = request.user
    form = BookmarkForm(initial={'author': current_user})
    context = {
        'bookmarks': bookmarks,
        'form': form,
    }
    return render(request, 'index.html', context)


def tag(request, tag_name):
    tag = get_object_or_404(Tag, slug=tag_name)
    bookmarks = tag.bookmarks.all()
    context = {
        'tag': tag,
        'bookmarks': bookmarks,
    }
    return render(request, 'tag.html', context)

myproject/bookmarks/templates/base.html
<!doctype html>
<html>
<head>
    <title>My bookmarking app</title>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/static/css/style.css" type="text/css" media="screen" charset="utf-8">
	<script src="/static/js/jquery-1.9.1.min.js"></script>
	<script src="/static/js/script.js"></script>
</head>
 
<body>
    <div id="container">
        <div id="header">
            {% block bookmark_widget %}
            {% endblock %}
            <div id="authentication">
            {% if user.is_authenticated %}
                Hi {{user}}! <a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'django.contrib.auth.views.login' %}">Login</a>
            {% endif %}
            </div>
            <h1><a href="/">My bookmarking app</a></h1>
        </div>
        <div id="content">
            <h2>{% block subheader %}{% endblock %}</h2>
            {% block content %}
            Sample content -- you should never see this, unless an inheriting template fails to have any content block!
            {% endblock %}
        </div>
        <div id="footer">
            Brought to you by PyCon US 2013
        </div>
    </div>
</body>
</html>

myproject/bookmarks/templates/bookmark.html
<li>
	<a class="bookmark-link" href="{{ bookmark.url }}">
	    {% if bookmark.title %}{{ bookmark.title }}{% else %}{{ bookmark.url }}{% endif %}
	</a>
	<div class="metadata"><span class="author">Posted by {{ bookmark.author }}</span> | <span class="timestamp">{{ bookmark.timestamp|date:"Y-m-d" }}</span>
	        {% if bookmark.tag_set.all %}| <span class="tags">
	            {% for tag in bookmark.tag_set.all %}
	                <a href="{% url 'bookmarks.views.tag' tag.slug %}">{{ tag.slug }}</a></span>
	            {% endfor %}
	        {% endif %}
	</div>
</li>

myproject/bookmarks/templates/index.html
{% extends 'base.html' %}
 
{% block subheader %}All bookmarks{% endblock %}
 
{% block content %}
<ul class="bookmarks">
    {% for bookmark in bookmarks %}
		{% include 'bookmark.html' %}
    {% endfor %}
</ul>
{% endblock %}
 
{% block bookmark_widget %}
    {% if user %}
    <div id="new-bookmark-widget">
        <form method="post">
		{% csrf_token %}
        <h3>Bookmark</h3>
        {{ form.as_p }}
        <p><button id="new-bookmark-submit">Submit</button>
        </form>
    </div>
    {% endif %}
{% endblock %}

myproject/bookmarks/templates/tag.html
{% extends 'index.html' %}
 
{% block subheader %}Bookmarks tagged {{ tag.slug }}{% endblock %}